import Link from "next/link";
import navItems from "./lib/navData.json";
import faqItems from "./lib/faqData.json";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h4>Layout:</h4>
          <h6>Main nav:</h6>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            {navItems.map((product) =>
              product.features.map((feature) =>
                feature.guides.map((guide) => (
                  <Link
                    key={guide.UUID}
                    style={{ display: "block" }}
                    href={`/${product.slug}/${feature.slug}/${guide.slug}`}
                  >
                    {product.title} - {feature.title} - {guide.title}
                  </Link>
                ))
              )
            )}
          </ul>
          <h6>FAQ nav:</h6>
          <ul>
            {faqItems.map((faq) => (
              <Link
                key={faq.UUID}
                style={{ display: "block" }}
                href={`/faq/${faq.productSlug}/${faq.featureSlug}/${faq.slug}`}
              >
                {faq.question}
              </Link>
            ))}
          </ul>
        </nav>
        <hr />
        <h6>Page content:</h6>
        {children}
      </body>
    </html>
  );
}
